name: booking_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: ^3.1.0
  ff_navigation_bar: ^0.1.5
  http: ^0.12.0+2
  line_icons: ^0.2.0
  flutter_slider_indicator: ^0.2.0
  date_field: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/PTSansNarrow-Bold.ttf
    - family: Lobster
      fonts:
        - asset: fonts/LobsterTwo-Regular.ttf
    - family: Patrick
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
